# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "Unit Tests & Coverage"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
        pip install -r requirements-ci.txt

    - name: Lint
      run: ./run-tests.sh -l

    - name: Unit tests
      run: ./run-tests.sh

    - name: Codacy
      run: python-codacy-coverage -r coverage.xml

    - name: Coveralls
      run: coveralls

    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash)
